version: '3'

vars:
  GIT_VERSION:
    sh: git describe --tags --abbrev=0 || echo "v0.0.0" | tr -d '\n'
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  BUILD_DATE:
    sh: date -u +'%Y-%m-%dT%H:%M:%SZ'

tasks:
  test:
    desc: Run tests
    aliases: [t]
    cmds:
      - go clean -testcache
      - go test -v -cover ./...
  
  coverage:
    desc: Run tests with coverage
    aliases: [c]
    cmds:
      - go clean -testcache
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out

  run:
    desc: Run the binary file
    aliases: [r]
    cmds:
      - go build -o ./bin/git-profile ./cmd/*.go && git-profile {{.CLI_ARGS}}

  build:
    desc: Build all binary files
    aliases: [b]
    cmds:
      - for:
        - { OS: linux, ARCH: amd64}
        - { OS: linux, ARCH: arm64}
        - { OS: windows, ARCH: amd64}
        - { OS: windows, ARCH: arm64}
        - { OS: darwin, ARCH: amd64}
        - { OS: darwin, ARCH: arm64}
        cmd: GOOS={{.ITEM.OS}} GOARCH={{.ITEM.ARCH}} go build -o ./build/git-profile-{{.GIT_VERSION}}-{{.ITEM.OS}}-{{.ITEM.ARCH}} -ldflags="-X main.gitVersion={{.GIT_VERSION}} -X main.gitCommit={{.GIT_COMMIT}} -X main.buildDate={{.BUILD_DATE}}" {{.CLI_ARGS}} ./cmd/*.go
